version: '3'

services:
  config-service:
    container_name: "config-service"
    build: "./config-service"
    ports:
      - "8888:8888"

  discovery-service:
    container_name: "discovery-service"
    build: "./discovery-service"
    ports:
      - "8761:8761"

  parser-service:
    container_name: "parser-service"
    build: "./parser-service"
    depends_on:
      - discovery-service
      - config-service
    ports:
      - "8081:8081"

  currency-service:
    container_name: "currency-service"
    build: "./currency-service"
    depends_on:
      - discovery-service
      - config-service
    ports:
      - "8080:8080"

  converter-service:
    container_name: "converter-service"
    build: "./converter-service"
    depends_on:
      - discovery-service
      - config-service
    ports:
      - "8082:8082"

