server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/maximdziuba/code/study/currency-microservices/config-service/src/main/resources/config

